title: Introduction to GitHub
tagline: Your sidekick for getting started on GitHub
description: If you are looking for a quick and fun introduction to GitHub, you've found it. This class will get you started using GitHub in less than an hour.
template:
  name: github-slideshow
  repo: caption-this-template
  description: 'A robot powered training repository :robot:'
preferences:
- type: radio
  name: gitTool
  label: Preferred Git tool
  description: Learn right from the web UI, or using your chosen tool
  options:
  - label: Use the GitHub.com web interface
    value: dotcom
  - label: Use the command line
    value: cli
  - label: Use Visual Studio Code
    value: vscode
before:
- type: updateBranchProtection
- type: createIssue
  title: Getting Started with GitHub
  body: introduction.md
  comments:
    - assign-yourself.md

# Course artifacts:
#   1. Issue: Getting started with GitHub
#   2. Issue: Your first contribution
#   3. PR: [Created by learner]

steps:

# 1
- title: Assign yourself
  description: Assign the first issue to yourself.
  event: issues.assigned
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: gate
    left: '%payload.assignee.login%'
    operator: ===
    right: '%user.username%'
  - type: respond
    with: turn-on-gh-pages.md

# 2
- title: Turn on GitHub Pages
  description: Turn on GitHub Pages in the settings page of the repository.
  event: page_build
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: octokit
    method: repos.getPages
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    action_id: pagesUrl
  - type: respond
    issue: Getting Started with GitHub
    with: close-issue.md
    data:
      pagesUrl: '%actions.pagesUrl.data.html_url%'

# 3
- title: Close an issue
  description: Cease a conversation by closing an issue.
  event: issues.closed
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: createIssue
    action_id: contrib_issue
    title: Your first contribution
    body: your-first-contribution.md
    comments:
      - create-a-branch.md
    data:
      thePayload: '%payload%'
  - type: respond
    with: head-to-branch.md
    data:
      issueURL: '%actions.contrib_issue.data.html_url%'

# 4
- title: Create a branch
  description: Create a branch for introducing new changes.
  event: create
  link: '{{ repoUrl }}/issues/2'
  actions:
  - type: respond
    issue: Your first contribution
    with: commit-something.md
    data:
      thePayload: '%payload%'

# 5
- title: Commit a file
  description: Commit your file to the branch.
  event: push
  link: '{{ repoUrl }}/issues/2'
  actions:
  - type: respond
    issue: Your first contribution
    with: open-a-pr.md
    data:
      branch: '%payload.ref%'
      url: '%payload.repository.html_url%/compare/%payload.ref%?expand=1'

# 6
- title: Open a pull request
  description: Open a pull request to propose your new file to the codebase.
  event: pull_request
  link: '{{ repoUrl }}/issues/2'
  actions:
  - type: gate
    gates:
    - left: '%payload.action%'
      operator: ===
      right: opened
    - left: '%payload.action%'
      operator: ===
      right: edited
    - left: '%payload.action%'
      operator: ===
      right: synchronize
  - type: closeIssue
    issue: Your first contribution
  - type: gate
    left: '%payload.pull_request.body%'
    else: 
    - type: createReview
      body: fix-body.md
      event: REQUEST_CHANGES
  - type: gate
    left: '%payload.pull_request.base.ref%'
    operator: ===
    right: master
    else:
    - type: createReview
      body: fix-base.md
      event: REQUEST_CHANGES
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/_posts\/\d{4}-\d{2}-\d{2}-%user.username%\.md/
    else:
    - type: createReview
      body: fix-filename.md
      event: REQUEST_CHANGES
      data:
        expected: _posts/0000-01-02-%user.username%.md
        url: '%payload.pull_request.html_url%/files'
  - type: createReview
    body: request-changes.md
    event: 'COMMENT'
    data:
      branch: '%payload.pull_request.head.ref%'
      url: '%payload.pull_request.html_url%/files'

# 7
- title: Respond to a review
  description: Respond to a PR review.
  event: pull_request.synchronize
  link: '{{ repoUrl }}/pull/3'
  actions:
  - type: removeBranchProtection
  - type: createReview
    body: pr-succeeds.md
    event: APPROVE
    data:
      branch: '%payload.pull_request.head.ref%'

# 8
- title: Merge your pull request
  description: Make your changes live by merging your PR.
  event: pull_request.closed
  link: '{{ repoUrl }}/pull/3'
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
    else:
      - type: respond
        with: reopen.md
  - type: respond
    with: reminder-delete.md

tags: [
  "Git","GitHub"
]
video: "sz6zfrQpCQg"
