title: "Introduction to GitHub"
tagline: "Your sidekick for getting started on GitHub"
description: "If you are looking for a quick and fun introduction to GitHub, you've found it. This class will get you started using GitHub in less than an hour."
template:
  name: "github-slideshow"
  repo: "caption-this-template"
  description: "A robot powered training repository :robot:"
preferences:
  - type: radio
    name: gitTool
    label: Preferred Git tool
    description: Learn right from the web UI, or using your chosen tool
    options:
      - label: Use the GitHub.com web interface
        value: dotcom
      - label: Use the command line
        value: cli
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Getting Started with GitHub
    body: "introduction.md"
    comments:
      - "assign-yourself.md"
steps:
  - title: "Assign yourself"
    description: "Assign the first issue to yourself."
    event: "issues.assigned"
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/issues/1
    actions:
      - type: gate
        left: "%payload.assignee.login%"
        operator: "==="
        right: "%user.username%"
      - type: respond
        with: "turn-on-gh-pages.md"

  - title: "Turn on GitHub Pages"
    description: "Turn on GitHub Pages in the settings page of the repository."
    event: "deployment"
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/settings
    actions:
      - type: respond
        issue: "Getting Started with GitHub"
        with: "close-issue.md"

  - title: Close an issue
    description: Cease a conversation by closing an issue.
    event: issues.closed
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/issues/1
    actions:
      - type: createIssue
        action_id: contrib_issue
        title: Your first contribution
        body: your-first-contribution.md
      - type: respond
        with: create-a-branch.md
        issue: '%actions.contrib_issue.data.title%'
        data:
          thePayload: '%payload%'
      - type: respond
        with: head-to-branch.md
        data:
          issueURL: '%actions.contrib_issue.data.html_url%'

  - title: "Create a branch"
    description: "Create a branch for introducing new changes."
    event: "create"
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/
    actions:
      - type: respond
        issue: "Your first contribution"
        with: commit-something.md
        data:
          thePayload: '%payload%'

  - title: "Commit a file"
    description: "Commit your file to the branch."
    event: "push"
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/
    actions:
      - type: respond
        issue: "Your first contribution"
        with: "open-a-pr.md"
        data:
          branch: "%payload.ref%"

  - title: "Open a pull request"
    description: "Open a pull request to propose your new file to the codebase."
    event: "pull_request"
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/compare?expand=1
    actions:
      - type: gate
        gates:
          - left: "%payload.action%"
            operator: "==="
            right: "opened"
          - left: "%payload.action%"
            operator: "==="
            right: "edited"
      - type: closeIssue
        issue: "Your first contribution"
      - type: createStatus
        state:
          left: "%payload.pull_request.body%"
        failure:
          description: Your pull request needs a description in the body. Please edit the pull request to include a body.
          target_url: https://help.github.com/articles/editing-a-comment/
        success:
          description: Your pull request has a body description.
          target_url: https://help.github.com/articles/creating-a-pull-request/#creating-the-pull-request
      - type: createStatus
        state:
          left: "%payload.pull_request.base.ref%"
          operator: "==="
          right: master
        success:
          description: Your pull request is based off of the master branch.
          target_url: https://help.github.com/articles/about-comparing-branches-in-pull-requests/
        failure:
          description: Your pull request is NOT based off of the master branch. Please close this pull request and open a new one.
          target_url: https://help.github.com/articles/about-comparing-branches-in-pull-requests/
      - type: gate
        left: "%payload.pull_request.body%"
        else:
          - type: createReview
            body: "fix-body.md"
            event: REQUEST_CHANGES
      - type: gate
        left: "%payload.pull_request.base.ref%"
        operator: "==="
        right: master
        else:
          - type: createReview
            body: "fix-base.md"
            event: REQUEST_CHANGES
      - type: getTree
      - type: createReview
        body: request-changes.md
        event: 'COMMENT'
        data:
          branch: '%payload.pull_request.head.ref%'


  - title: "Respond to a review"
    description: "Respond to a PR review."
    event: "pull_request.synchronize"
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pull/3
    actions:
      - type: removeBranchProtection
      - type: createStatus
        state:
          left: "%pull_request.body%"
        failure:
          description: Your pull request needs a description in the body. Please edit the pull request to include a body.
          target_url: https://help.github.com/articles/editing-a-comment/
        success:
          description: Your pull request has a body description.
          target_url: https://help.github.com/articles/creating-a-pull-request/#creating-the-pull-request
      - type: createStatus
        state:
          left: "%payload.pull_request.base.label%"
          operator: "==="
          right: "%user.username%:master"
        success:
          description: Your pull request is based off of the master branch.
          target_url: https://help.github.com/articles/about-comparing-branches-in-pull-requests/
        failure:
          description: Your pull request is NOT based off of the master branch. Please close this pull request and open a new one.
          target_url: https://help.github.com/articles/about-comparing-branches-in-pull-requests/
      - type: createReview
        body: pr-succeeds.md
        event: APPROVE
        data:
          branch: '%payload.pull_request.head.ref%'

  - title: "Merge your pull request"
    description: "Make your changes live by merging your PR."
    event: "pull_request.closed"
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pull/3
    actions:
      - type: gate
        left: "%payload.pull_request.merged%"
        else:
          - type: respond
            with: "reopen.md"
      - type: respond
        with: "reminder-delete.md"

tags: [
  "Git","GitHub"
]
video: "sz6zfrQpCQg"
